#ifndef GUIMyFrame1_H
#define GUIMyFrame1_H

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/generic/filedlgg.h>
#include <wx/dcbuffer.h>
#include <FreeImage.h>
#include <CImg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MyFrame1OnUpdateUI( wxUpdateUIEvent& event ) override;
		void MyFrame1OnSize( wxSizeEvent& event ) override;
		void btn_loadOnButtonClick( wxCommandEvent& event ) override;
		void btn_censorOnButtonClick( wxCommandEvent& event ) override;
		void btn_erodeOnButtonClick( wxCommandEvent& event ) override;
		void check_animationOnCheckBox( wxCommandEvent& event ) override;
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void ScaleImage();
		void Repaint();
		void SwitchControls(bool status);
		void ProcessExif(const char* path);

		wxImage imgOrg;
		wxImage imgCopy;
		wxBitmap animationFrames[360];

		bool erode;
		bool censor;
		bool animation_running;

};

#endif // GUIMyFrame1
